docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - "Quick Start": quick-start.md
    - "Rendering Views":
        - "The PhpRenderer": php-renderer.md
        - "View Scripts": view-scripts.md
        - "The ViewEvent": view-event.md
    - Helpers:
        - Introduction: helpers/intro.md
        - Asset: helpers/asset.md
        - BasePath: helpers/base-path.md
        - Cycle: helpers/cycle.md
        - Doctype: helpers/doctype.md
        - Escape: helpers/escape.md
        - FlashMessenger: helpers/flash-messenger.md
        - Gravatar: helpers/gravatar.md
        - HeadLink: helpers/head-link.md
        - HeadMeta: helpers/head-meta.md
        - HeadScript: helpers/head-script.md
        - HeadStyle: helpers/head-style.md
        - HeadTitle: helpers/head-title.md
        - HtmlList: helpers/html-list.md
        - HtmlObject: helpers/html-object.md
        - HtmlTag: helpers/html-tag.md
        - Identity: helpers/identity.md
        - InlineScript: helpers/inline-script.md
        - Json: helpers/json.md
        - Layout: helpers/layout.md
        - Partial: helpers/partial.md
        - Placeholder: helpers/placeholder.md
        - Url: helpers/url.md
        - "Advanced usage of helpers": helpers/advanced-usage.md
    - Cookbook:
        - "Setting module-specific Layouts": cookbook/setting-module-specific-layouts.md
site_name: laminas-view
site_description: 'Flexible view layer supporting and providing multiple view layers, helpers, and more.'
repo_url: 'https://github.com/laminas/laminas-view'
extra:
    project: Components
    project_url: 'https://docs.laminas.dev'
